-- 002_seed_admin.sql
-- Purpose: Seed an initial admin user for first-time login.
-- IMPORTANT: Replace the placeholder hashed_password with a real bcrypt hash via backend or deployment pipeline.

-- Example placeholder: bcrypt hash of "ChangeMe123!" should be generated by backend.
-- Do NOT keep this placeholder in production.

WITH maybe_admin AS (
    SELECT id FROM public.users WHERE LOWER(email) = LOWER('admin@example.com')
)
INSERT INTO public.users (email, hashed_password, full_name, role, is_active, is_superuser)
SELECT 'admin@example.com',
       '$2b$12$PLACEHOLDER_HASH_REPLACE_ME',  -- Replace with real bcrypt hash
       'Administrator',
       'admin',
       TRUE,
       TRUE
WHERE NOT EXISTS (SELECT 1 FROM maybe_admin);
